openapi: 3.0.3
info:
  title: "Vulpecula Movie Diary ${VERSION_APP}"
  description: Movie Diary for Cinemaphiles
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8081/v1
tags:
  - name: movie
    description: Movie
paths:
  /movie/search:
    post:
      tags:
        - movie
      summary: Search a movie and save it to DB
      operationId: movieSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieSearchResponse'
  /movie/read:
    post:
      tags:
        - movie
      summary: Read a movie
      operationId: movieRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieReadResponse'

components:
  schemas:

    IRequest:
      type: object
      description: Basic request interface
      properties:
        requestType:
          type: string
          description: Discriminator field to determine the request type
          example: create
      discriminator:
        propertyName: requestType
        mapping:
          search: '#/components/schemas/MovieSearchRequest'
          read:   '#/components/schemas/MovieReadRequest'

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Basic response interface
      properties:
        responseType:
          type: string
          description: Discriminator field to determine the response type
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      discriminator:
        propertyName: responseType
        mapping:
          search: '#/components/schemas/MovieSearchResponse'
          read:   '#/components/schemas/MovieReadResponse'
          init: '#/components/schemas/MovieInitResponse'

    MovieId:
      type: string
      description: Movie Identifier

    MovieInitResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'

    MovieReadObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/MovieId'

    MovieReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/MovieRequestDebug'
        - type: object
          properties:
            movie:
              $ref: '#/components/schemas/MovieReadObject'

    MovieSearchFilter:
      type: object
      description: Search filters
      properties:
        searchString:
          type: string
          minLength: 1
          maxLength: 200
          description: Search string

    MovieSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/MovieRequestDebug'
        - type: object
          properties:
            movieFilter:
              $ref: '#/components/schemas/MovieSearchFilter'

    MovieResponseObject:
      allOf:
        - type: object
          description: Movie object from external API
          properties:
            id:
              $ref: '#/components/schemas/MovieId'
            title:
              type: string
              maxLength: 500
              description: Movie title
            releaseYear:
              type: integer
              maximum: 2100
              description: Movie release year
            director:
              type: array
              items:
                type: string
                maxLength: 200
              description: Movie directors
            cast:
              type: array
              items:
                type: string
                maxLength: 200
              description: Movie cast
            genre:
              type: array
              items:
                type: string
                maxLength: 200
              description: Movie genres
            synopsis:
              type: string
              maxLength: 2000
              description: Movie synopsis
            posterUrl:
              type: string
              format: uri
              maxLength: 2048
              pattern: '^https?://.+'
              description: Movie poster URL
            tmdbId:
              type: integer
              description: TMDb movie ID

    MovieResponseSingle:
      allOf:
        - type: object
          description: Response with one movie object
          properties:
            movie:
              $ref: '#/components/schemas/MovieResponseObject'

    MovieResponseMulti:
      allOf:
        - type: object
          description: Response with several movie objects
          properties:
            movies:
              type: array
              items:
                $ref: '#/components/schemas/MovieResponseObject'

    MovieReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/MovieResponseSingle'

    MovieSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/MovieResponseMulti'

    # STUBS ======================
    MovieRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    MovieRequestDebug:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/MovieDebug'

    MovieDebug:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/MovieRequestDebugMode'
        stub:
          $ref: '#/components/schemas/MovieRequestDebugStubs'

    MovieRequestDebugStubs:
      type: string
      description: List of all stubs
      enum:
        - success
        - notFound
        - badId
        - badTitle
        - badReleaseYear
        - badDirector
        - badCast
        - badGenre
        - badSynopsis
        - badPosterUrl
        - badTmdbId
        - badSearchString
        - dbError