openapi: 3.0.3
info:
  title: "Vulpecula Movie Diary ${VERSION_APP}"
  description: Movie Diary for Cinemaphiles
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: entry
    description: Diary Entry
paths:
  /entry/create:
    post:
      tags:
        - entry
      summary: Create an entry
      operationId: entryCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryCreateResponse'
  /entry/read:
    post:
      tags:
        - entry
      summary: Read an entry
      operationId: entryRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryReadResponse'
  /entry/update:
    post:
      tags:
        - entry
      summary: Update an entry
      operationId: entryUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryUpdateResponse'
  /entry/delete:
    post:
      tags:
        - entry
      summary: Delete an entry
      operationId: entryDelete
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryDeleteRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryDeleteResponse'
  /entry/search:
    post:
      tags:
        - entry
      summary: Search an entry
      operationId: entrySearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntrySearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntrySearchResponse'

components:
  schemas:

    IRequest:
      type: object
      description: Basic request interface
      properties:
        requestType:
          type: string
          description: Discriminator field to determine the request type
          example: create
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/EntryCreateRequest'
          read:   '#/components/schemas/EntryReadRequest'
          update: '#/components/schemas/EntryUpdateRequest'
          delete: '#/components/schemas/EntryDeleteRequest'
          search: '#/components/schemas/EntrySearchRequest'

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Basic response interface
      properties:
        responseType:
          type: string
          description: Discriminator field to determine the response type
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/EntryCreateResponse'
          read:   '#/components/schemas/EntryReadResponse'
          update: '#/components/schemas/EntryUpdateResponse'
          delete: '#/components/schemas/EntryDeleteResponse'
          search: '#/components/schemas/EntrySearchResponse'
          init: '#/components/schemas/EntryInitResponse'

    UserId:
      type: string
      description: User Identifier

    MovieId:
      type: string
      description: Movie Identifier

    EntryId:
      type: string
      description: Entry Identifier

    EntryLock:
      type: string
      description: Optimistic lock version

    BaseEntry:
      type: object
      description: Common properties for create and update operations
      properties:
        movieId:
          $ref: '#/components/schemas/MovieId'
        viewingDate:
          type: string
          format: date
          description: Movie viewing date
        rating:
          type: integer
          minimum: 1
          maximum: 10
          description: Movie rating (1-10)
        comment:
          type: string
          minLength: 3
          maxLength: 2000
          description: User comment about movie

    EntryInitResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'

    EntryCreateObject:
      allOf:
        - $ref: '#/components/schemas/BaseEntry'

    EntryCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/EntryRequestDebug'
        - type: object
          properties:
            entry:
              $ref: '#/components/schemas/EntryCreateObject'

    EntryReadObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/EntryId'

    EntryReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/EntryRequestDebug'
        - type: object
          properties:
            entry:
              $ref: '#/components/schemas/EntryReadObject'

    EntryUpdateObject:
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/EntryId'
            lock:
              $ref: '#/components/schemas/EntryLock'

    EntryUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/EntryRequestDebug'
        - type: object
          properties:
            entry:
              $ref: '#/components/schemas/EntryUpdateObject'

    EntryDeleteObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/EntryId'
            lock:
              $ref: '#/components/schemas/EntryLock'

    EntryDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/EntryRequestDebug'
        - type: object
          properties:
            entry:
              $ref: '#/components/schemas/EntryDeleteObject'

    EntrySearchFilter:
      type: object
      description: Search filters
      properties:
        searchString:
          type: string
          description: Search string
        movieId:
          $ref: '#/components/schemas/MovieId'
        viewingDateFrom:
          type: string
          format: date
          description: Start date for filtering
        viewingDateTo:
          type: string
          format: date
          description: End date for filtering

    EntrySearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/EntryRequestDebug'
        - type: object
          properties:
            entryFilter:
              $ref: '#/components/schemas/EntrySearchFilter'

    EntryResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          description: Response object returned by backend
          properties:
            id:
              $ref: '#/components/schemas/EntryId'
            userId:
              $ref: '#/components/schemas/UserId'
            lock:
              $ref: '#/components/schemas/EntryLock'
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/EntryPermissions'

    EntryPermissions:
      type: string
      description: User permissions for diary entry operations
      enum:
        - read
        - update
        - delete

    EntryResponseSingle:
      allOf:
        - type: object
          description: Response with one entry object
          properties:
            entry:
              $ref: '#/components/schemas/EntryResponseObject'

    EntryResponseMulti:
      allOf:
        - type: object
          description: Response with several entry objects
          properties:
            entries:
              type: array
              items:
                $ref: '#/components/schemas/EntryResponseObject'

    EntryCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/EntryResponseSingle'

    EntryReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/EntryResponseSingle'

    EntryUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/EntryResponseSingle'

    EntryDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/EntryResponseSingle'

    EntrySearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/EntryResponseMulti'

    # STUBS ======================
    EntryRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    EntryRequestDebug:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/EntryDebug'

    EntryDebug:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/EntryRequestDebugMode'
        stub:
          $ref: '#/components/schemas/EntryRequestDebugStubs'

    EntryRequestDebugStubs:
      type: string
      description: List of all stubs
      enum:
        - success
        - notFound
        - badId
        - badMovieId
        - badRating
        - badViewingDate
        - badComment
        - cannotDelete
        - badSearchString