changeLogFile=changelog/changelog-v0.0.1.sql
liquibase.command.url=jdbc:postgresql://localhost:5432/vulpecula_entries
liquibase.command.username=postgres
liquibase.command.password=vulpecula-pass
liquibase.liquibaseSchemaName=public
